import type { RatesMap } from './types';

export const FALLBACK_RATES: RatesMap = {
  EUR: { code: 'EUR', name: 'Euro', flag: 'eu', buy: 1, sell: 1, send: 1 },
  USD: { code: 'USD', name: 'US Dollar', flag: 'us', buy: 0.83, sell: 0.865, send: undefined },
  TRY: { code: 'TRY', name: 'Turkish Lira', flag: 'tr', buy: 52, sell: 50, send: undefined },
  GBP: { code: 'GBP', name: 'British Pound', flag: 'gb', buy: 1.1, sell: 1.16, send: undefined },
  CAD: { code: 'CAD', name: 'Canadian Dollar', flag: 'ca', buy: 0.56, sell: 0.64, send: undefined },
  AUD: { code: 'AUD', name: 'Australian Dollar', flag: 'au', buy: 0.51, sell: 0.58, send: undefined },
  AED: { code: 'AED', name: 'UAE Dirham', flag: 'ae', buy: 0.21, sell: 0.265, send: undefined },
  JOD: { code: 'JOD', name: 'Jordanian Dinar', flag: 'jo', buy: 1.19, sell: 1.25, send: undefined },
  SAR: { code: 'SAR', name: 'Saudi Riyal', flag: 'sa', buy: 0.22, sell: 0.25, send: undefined },
  QAR: { code: 'QAR', name: 'Qatari Riyal', flag: 'qa', buy: 0.222, sell: 0.252, send: undefined },
  KWD: { code: 'KWD', name: 'Kuwaiti Dinar', flag: 'kw', buy: 2.7, sell: 3, send: undefined },
  ILS: { code: 'ILS', name: 'Israeli Shekel', flag: 'il', buy: 0.22, sell: 0.25, send: undefined },
  PLN: { code: 'PLN', name: 'Polish Zloty', flag: 'pl', buy: 0.18, sell: 0.23, send: undefined },
  SEK: { code: 'SEK', name: 'Swedish Krona', flag: 'se', buy: 0.07, sell: 0.089, send: undefined },
  CHF: { code: 'CHF', name: 'Swiss Franc', flag: 'ch', buy: 0.96, sell: 1.06, send: undefined },
  RUB: { code: 'RUB', name: 'Russian Ruble', flag: 'ru', buy: 0.007, sell: 0.01, send: undefined },
  PHP: { code: 'PHP', name: 'Philippine Peso', flag: 'ph', buy: 0.0079, sell: 0.0158, send: undefined },
  EGP: { code: 'EGP', name: 'Egyptian Pound', flag: 'eg', buy: 0.014, sell: 0.019, send: 57 },
  BGN: { code: 'BGN', name: 'Bulgarian Lev', flag: 'bg', buy: 0.4, sell: 0.511, send: undefined },
  INR: { code: 'INR', name: 'Indian Rupee', flag: 'in', buy: 0.0057, sell: 0.011, send: undefined },
  GEL: { code: 'GEL', name: 'Georgian Lari', flag: 'ge', buy: 0.18, sell: 0.35, send: undefined },
  OMR: { code: 'OMR', name: 'Omani Rial', flag: 'om', buy: 2.1, sell: 2.4, send: undefined },
  RON: { code: 'RON', name: 'Romanian Leu', flag: 'ro', buy: 0.1, sell: 0.2, send: undefined },
  NOK: { code: 'NOK', name: 'Norwegian Krone', flag: 'no', buy: 0.045, sell: 0.086, send: undefined },
  BHD: { code: 'BHD', name: 'Bahraini Dinar', flag: 'bh', buy: 1.8, sell: 2.51, send: undefined },
  IRR: { code: 'IRR', name: 'Iranian Rial', flag: 'ir', buy: undefined, sell: undefined, send: undefined },
  UAH: { code: 'UAH', name: 'Ukrainian Hryvnia', flag: 'ua', buy: undefined, sell: undefined, send: undefined },
  BDT: { code: 'BDT', name: 'Bangladeshi Taka', flag: 'bd', buy: undefined, sell: undefined, send: undefined },
  PKR: { code: 'PKR', name: 'Pakistani Rupee', flag: 'pk', buy: 0.002, sell: 0.0034, send: undefined },
};
